# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopBack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShopBack
  pod 'KRPullLoader'
#  pod 'KVNProgress'

  target 'ShopBackTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShopBackUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'KRPullLoader'
  end

end
